config/routes.rb
Rails.application.routes.draw do

  root 'events#index'
  get 'register'  => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'createnewevent' => 'events#createnewevent'
  get 'showevent' => 'events#show'
  resources :events
  resources :users
  
 # post 'events/id' => 'events#create'
  

end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id            :integer          not null, primary key
#  name          :string
#  date_of_event :datetime
#  fee           :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Event < ActiveRecord::Base
  has_many :user_and_events
	has_many :users, through: :user_and_events
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string
#  email           :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string
#  password        :string
#  gender          :string
#

class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
  
   has_many :user_and_events
    has_many :events, through: :user_and_events
end

app/models/user_and_event.rb
# == Schema Information
#
# Table name: user_and_events
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  event_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class UserAndEvent < ActiveRecord::Base
  belongs_to :user
	belongs_to :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found

  def record_not_found
  	redirect_to(current_user)
  end
  
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def new
  end
  
  def index
    @events = Event.all.order(created_at: :desc)
  end


  def show
  	@event = Event.find(params[:id])
  	@user = current_user
  	@all_attendies = User.joins(:user_and_events).where('user_and_events.event_id = ?', params[:id])
  
  	if logged_in?
    	@user_event = User.joins(:user_and_events).where('user_and_events.event_id = ? AND user_and_events.user_id = ?', params[:id], current_user.id)
    end  
  end

  def createnewevent
    @temp = UserAndEvent.new(:user_id => current_user.id, :event_id => params[:id])
    @temp.save 
     redirect_to event_path(:id => params[:id])
   
  end
  
  def destroy
    UserAndEvent.where("user_id = ? AND event_id = ?", current_user.id, params[:id]).first.delete
    redirect_to :action => 'show' 
  end
  
 private
  	def past_event?(event_dt)
  	    date = Date.parse event_dt
  	    date.past?
  	end

  	helper_method :past_event?
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create 
  		user = User.find_by(email: params[:session][:email].downcase)
    	if user && user.authenticate(params[:session][:password])
      	log_in user
        redirect_to user
    	else
      		flash.now[:danger] = 'Invalid email/password combination' 
      		render 'new'
    	end
    end
    
  	def destroy
        log_out
        redirect_to root_url
  	end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   
  before_action :logged_in_user, only: [:edit, :update, :show]
  before_action :correct_user, only: [:edit, :update, :show]
  def new
    @user = User.new
  end

  def index
    redirect_to(current_user)
  end
  def show
    @user = User.find(params[:id])
  end
  

	def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  private

  	def user_params
    		params.require(:user).permit(:name, :email, :password, :password_confirmation, :gender)
  	end

    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in"
        redirect_to login_url
      end
    end
    def correct_user
      @user = User.find(params[:id])
      redirect_to(current_user) unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		@current_user||=User.find_by(id: session[:user_id])
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end

	def current_user?(user)
		user == current_user
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<% provide(:title, 'Home Page - Displaying Events') %>
<h1>Events</h1>
<h3> Click on link to view and attend event <h3>

<table class="table table-bordered">
	<tr>
		<th>Name of Event</th>
		<th>Created Date (From Most Recent)</th>
		
	</tr>
	<% @events.each do |events| %>
			<tr>
				<td><%= link_to events.name, event_path(:id => events.id) %></td>
				<td><%= events.created_at.strftime("Created: %m/%d/%Y") %></td>
			<tr>
	<%end%>
</table>

app/views/events/new.html.erb
<h1>Events#new</h1>
<p>Find me in app/views/events/new.html.erb</p>

app/views/events/show.html.erb
<% provide(:title, @event.name) %>
<div class="row">
  <aside class="col-md-4">
   	<section class="user_info">
    	<h3>
       	Name: <%= @event.name %>
    	</h3>
    	<h4>
       	Occurance Date of Event: <%= @event.date_of_event.strftime("%m/%d/%Y") %>
    	</h4>
    </section>
    <br/>
    <% if logged_in? %>
      <% if !past_event? @event.date_of_event.strftime("%d/%m/%Y") %>
         <% if @user_event.first.present? %>
          <h3><%= link_to "delete attendence",  event_path, method: :delete %></h3>
         <% else %>
         	 <h3><%= link_to "attend",  createnewevent_path(:id => @event.id) %></h3>
        <% end %>
      <% else %>
        <h4>You cannot attend this event as it has already occured</h4>
      <% end %>
      <% else %>
        <h4>Please Log in if you want to attend this event!</h4>
    <% end %>
  </aside>
   <div class="col-md-6">
    <% if @all_attendies.count > 0%>
      <table class="table table-bordered">
        <tr>
          <th>Name</th>
          <th>Gender</th>
          <th>Fees</th>
        </tr>
        <% @all_attendies.each do |user| %>
          <tr>
            <td><%= user.name%></td>
            <td><%= user.gender%></td>
            <% if(user.gender == "female") %>
              <td><%= 0.95 * @event.fee%> (Discount)</td>
            <% else %>
              <td><%= @event.fee%></td>
            <% end %>
          </tr>
  	     <% end %>
      </table>
    <% else %>
      <h4>This event has zero attendance</h4>
    <%end%>
   </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
    
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <ul class="nav navbar-nav navbar-center">
      	<li><%= link_to "Home",  events_path %></li>
        <% if logged_in? %>
         	<li><%= link_to "Log Out", logout_path, method: "delete" %></li>
        <% else %>
        	<li><%= link_to "Log in", login_path %></li>
          <li><%= link_to "Register", register_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
      <title><%= yield(:title) %></title>
      <%= stylesheet_link_tag 'application', media: 'all','data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>

    </head>
    <body>
      <%= render 'layouts/header' %>
      <div class="container">
          <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>"><%= message %></div>
          <% end %>
          <%= yield %>
          <%= render 'layouts/footer' %>
          <%= debug(params) if Rails.env.development? %>
      </div>
    </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@user.errors.count, "error") %>.
      </div>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Register') %>
<h1>Register</h1>

<div class="row">
  	<div class="col-md-6 col-md-offset-3">
    	<%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>

      		<%= f.label :name %>
      		<%= f.text_field :name %>
          

      		<%= f.label :email %>
      		<%= f.email_field :email %>

	    	<%= f.label :password %>
      		<%= f.password_field :password %>

      		<%= f.label :password_confirmation, "Confirmation" %>
      		<%= f.password_field :password_confirmation %>

      		<%= f.label :gender %>
      		<%= f.select :gender ,[["--Please Select your gender--",""],["Male","male"],["Female","female"]] %>

      		<%= f.submit "Create my account", class: "btn btn-primary" %>
    	<% end %>
  	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  	<aside class="col-md-4">
    	<section class="user_info">
      	<h1>
        	Welcome <%= @user.name %>
      	</h1>
      	<p>Please click on home to view all the available events.</p>
    	</section>
  	</aside>
</div>